name: CI Pipeline

on:
  push:
    branches:
      - main  # Or any other branch you want
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight (UTC)

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Adjust to your preferred version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Or `pip install tox` if you manage dependencies that way
        pip install tox  # If you didn't include tox in `requirements.txt`

    - name: Run linters (flake8)
      run: |
        tox -e lint  # Runs flake8 as part of tox
